config/routes.rb
Up::Application.routes.draw do
  get "welcome/index"

  resources :brothers

   root :to => 'welcome#index'

end

app/models/brother.rb
class Brother < ActiveRecord::Base
  attr_accessible :addr1, :addr2, :birthdate, :cellphone, :cep, :comphone, :date1, :date2, :date3, :degree, :name, :resphone
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Clearance::Authentication
	protect_from_forgery


	
end

app/controllers/brothers_controller.rb
class BrothersController < ApplicationController
  # GET /brothers
  # GET /brothers.json
  def index
    @brothers = Brother.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brothers }
    end
  end

  # GET /brothers/1
  # GET /brothers/1.json
  def show
    @brother = Brother.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brother }
    end
  end

  # GET /brothers/new
  # GET /brothers/new.json
  def new
    @brother = Brother.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brother }
    end
  end

  # GET /brothers/1/edit
  def edit
    @brother = Brother.find(params[:id])
  end

  # POST /brothers
  # POST /brothers.json
  def create
    @brother = Brother.new(params[:brother])

    respond_to do |format|
      if @brother.save
        format.html { redirect_to @brother, notice: 'Cadastro atualizado com sucesso.' }
        format.json { render json: @brother, status: :created, location: @brother }
      else
        format.html { render action: "new" }
        format.json { render json: @brother.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brothers/1
  # PUT /brothers/1.json
  def update
    @brother = Brother.find(params[:id])

    respond_to do |format|
      if @brother.update_attributes(params[:brother])
        format.html { redirect_to @brother, notice: 'Cadastro atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brother.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brothers/1
  # DELETE /brothers/1.json
  def destroy
    @brother = Brother.find(params[:id])
    @brother.destroy

    respond_to do |format|
      format.html { redirect_to brothers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brothers_helper.rb
module BrothersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brothers/_form.html.erb
<%= form_for @brother, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :addr1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :addr1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :addr2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :addr2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cep, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cep, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :resphone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :resphone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cellphone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cellphone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comphone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comphone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :birthdate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :birthdate, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date3, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date3, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :degree, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :degree, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                brothers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/brothers/edit.html.erb
<%- model_class = Brother -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brothers/index.html.erb
<% if signed_in? -%>

<%- model_class = Brother -%>
<div class="page-header">
  <h2>Cadastro dos <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:comphone) %></th>
      <th><%= model_class.human_attribute_name(:cellphone) %></th>
      <th><%= model_class.human_attribute_name(:birthdate) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @brothers.each do |brother| %>
      <tr>
        <td><%= link_to brother.id, brother_path(brother) %></td>
        <td><%= brother.name %></td>
        <td><%= brother.comphone %></td>
        <td><%= brother.cellphone %></td>
        <td><%= brother.birthdate %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_brother_path(brother), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      brother_path(brother),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_brother_path,
            :class => 'btn btn-primary' %>

<% end -%>

app/views/brothers/new.html.erb
<%- model_class = Brother -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brothers/show.html.erb
<%- model_class = Brother -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @brother.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:addr1) %>:</strong></dt>
  <dd><%= @brother.addr1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:addr2) %>:</strong></dt>
  <dd><%= @brother.addr2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cep) %>:</strong></dt>
  <dd><%= @brother.cep %></dd>
  <dt><strong><%= model_class.human_attribute_name(:resphone) %>:</strong></dt>
  <dd><%= @brother.resphone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cellphone) %>:</strong></dt>
  <dd><%= @brother.cellphone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comphone) %>:</strong></dt>
  <dd><%= @brother.comphone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birthdate) %>:</strong></dt>
  <dd><%= @brother.birthdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date1) %>:</strong></dt>
  <dd><%= @brother.date1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date2) %>:</strong></dt>
  <dd><%= @brother.date2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date3) %>:</strong></dt>
  <dd><%= @brother.date3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:degree) %>:</strong></dt>
  <dd><%= @brother.degree %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              brothers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_brother_path(@brother), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              brother_path(@brother),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt"
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UP Digital" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>


    <% if signed_in? -%>

      <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">       UP Digital</a>
            <div class="container nav-collapse">
              <ul class="nav">

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Eu na UP<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Meu Cadastro</a></li>
                    <li><a href="#">Meus Familiares</a></li>
                    <li><a href="#">Certificados de Presença</a></li>
                    <li><a href="#">Minhas Graduações</a></li>
                    <li><a href="#">Comissões que Faço Parte</a></li>
                    <li><a href="#">Cargos que já Fiz</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Minha Situação Atual</li>
                    <li><a href="#">Biblioteca</a></li>
                    <li><a href="#">Financeiro e Boletos  </a></li>
                    <li><a href="#">Presença nas Sessões</a></li>
                  </ul>
                </li>


                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<b class="caret"></b></a>
                  <ul class="dropdown-menu">

                    <li><a href="#">Sessões</a></li>
                    <li><a href="#">Frequência</a></li>
                    <li><a href="#">Certificados de Presença</a></li>
                    <li><a href="#">Eventos</a></li>
                    <li><a href="/brothers">Obreiros</a></li>
                    <li><a href="/brothers">Graduações</a></li>
                    <li><a href="#">Familiares</a></li>
                    <li><a href="#">Comissões Instituídas</a></li>
                    <li><a href="#">Cargos em Loja</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Biblioteca</li>
                    <li><a href="#">Acervo</a></li>
                    <li><a href="#">Empréstimos e Devoluções</a></li>
                    <li><a href="http://www.ritobrasileirogob.com.br/portal/">Trabalhos apresentados em Loja</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Financeiro</li>
                    <li><a href="#">Despesas da Loja</a></li>
                    <li><a href="#">Receitas da Loja</a></li>
                    <li><a href="#">Tronco de Beneficência</a></li>
                    <li><a href="#">Uso do Tronco de Beneficência</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Configurações</li>
                    <li><a href="#">Usuários do Sistema</a></li>
                  </ul>
                </li>


                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consultas<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Quadro de Obreiros</a></li>
                    <li><a href="#">Telefones</a></li>
                    <li><a href="#">Calendário da Loja</a></li>
                    <li><a href="#">Aniversariantes do Mês</a></li>
                    <li><a href="#">Comissões Ativas</a></li>
                    <li><a href="#">Frequência e Adimplência</a></li>
                    <li><a href="#">Acervo da Biblioteca</a></li>
                    <li><a href="#">Livros Emprestados</a></li>
                    <li><a href="#">Situação Financeira da Loja</a></li>
                    <li><a href="#">Uso do Tronco de Beneficência</a></li>
                    <li><a href="http://www.ritobrasileirogob.com.br/portal/">Trabalhos apresentados em Loja</a></li>

                  </ul>
                </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Legislação<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="http://gob-sc.org.br">Postulados da Loja União e Prosperidade</a></li>
                    <li><a href="http://gob-sc.org.br">Constituição GOB-SC</a></li>
                    <li><a href="http://gob-sc.org.br">Constituição GOB</a></li>
                    <li><a href="http://gob.org.br">Regulamento Geral da Federação</a></li>
                    <li><a href="http://www.ritobrasileirogob.com.br/portal/">VADE-MECUM Atualizado</a></li>
                  </ul>
                </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Links Úteis<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="http://gob.org.br">Grande Oriente do Brasil</a></li>
                    <li><a href="http://gob-sc.org.br">GOB-SC</a></li>
                    <li><a href="http://www.ritobrasileirogob.com.br/portal/">Supremo Conclave para o Rito Brasileiro</a></li>
                  </ul>
                </li>

                <li class="link">
                  <%= link_to "Sair", sign_out_path, :method => :delete %>
                </li>
              </ul>

            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="container">
          <div class="row">
            <div class="span9">
              <br>
              <br>
              <%= bootstrap_flash %>
              <%= yield %>
    <footer>
      <br>
        <p align=center>&copy; Loja União e Prosperidade 2013 - Todos os direitos reservados.</p>
    </footer>
            </div>
          </div><!--/row-->
      </div> <!-- /container -->

    <% else -%>
      <br>

      <center><h3>Portal UP Digital</h3>
        <div class="article-content">
          <p style="text-align: center;"><img width=300 src="/up.png" alt="União e Prosperidade"></p>
      </div>
      <div id="flash" align="center">
              <%= bootstrap_flash %>
              <%= yield %>
    <footer>
      <br>
        <p align=center>&copy; Loja União e Prosperidade 2013 - Todos os direitos reservados.</p>
    </footer>
      </div>
      </center>


    <% end -%>



    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

<!--
Venerável
Secretário
Orador
Vigilante 1
Vigilante 2
M. Cerimônia
Diácono 1
Diácolo 2
Tesoureiro
Chanceler
Hospitaleiro
Harmonia
Cobridor
Experto 1
Experto 2
>

app/views/users/_form.html.erb
<div class="text_field">
  <%= form.label :email %>
  <%= form.text_field :email, :type => "email" %>
</div>
<div class="password_field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<h4>Cadastro no Portal</h4>

<%= form_for @user do |form| %>
  <%= render :partial => '/users/form', :object => form %>
  <br>
  <button type="submit" class="btn btn-primary">Registrar-se</button>
  <br>
<% end %>

app/views/welcome/index.html.erb

<% if signed_in? -%>
	<h3><center>Seja bem-vindo à UP Digital</center></h3>
	<div class="article-content"> 
		<p style="text-align: center;"><img src="/up.png" alt="União e Prosperidade"></p>
	</div>
<% else -%>
	<%= render :partial => '/sessions/form' %>
	<ul>
  	<li>
	    <%= link_to "Registrar-se", sign_up_path %> 
  	</li>
  	<li>
	    <%= link_to "Esqueceu sua senha ?", new_password_path %>
  	</li>
	</ul>
<% end -%>

